1. Cargar los datos
2. Exploración inicial
3. Limpieza de Datos
4. Medallas de País
5. Medallas Totales por País

In [2]:
# 1. Cargar los datos

import pandas as pd
df = pd.read_csv('source/medallas.csv')

In [3]:
# 2. Exploración Inicial

df.shape
df.columns
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Oro     65 non-null     float64
 1   Plata   69 non-null     float64
 2   Bronce  76 non-null     float64
 3   Total   93 non-null     int64
 4   Pais    93 non-null     str
dtypes: float64(3), int64(1), str(1)
memory usage: 3.8 KB

    Oro  Plata  Bronce  Total        Pais
0   NaN    1.0     2.0      3   Argentina
1   NaN    2.0     2.0      4     Armenia
2  17.0    7.0    22.0     46   Australia
3   1.0    1.0     5.0      7     Austria
4   NaN    3.0     4.0      7  Azerbaijan

In [4]:
# 3. Limpieza de Datos

df.isnull().sum()
df = df.fillna(0)
df[['Oro', 'Plata', 'Bronce']] = df[['Oro', 'Plata', 'Bronce']].astype(int)
df.head()

   Oro  Plata  Bronce  Total        Pais
0    0      1       2      3   Argentina
1    0      2       2      4     Armenia
2   17      7      22     46   Australia
3    1      1       5      7     Austria
4    0      3       4      7  Azerbaijan

In [7]:
# 4. Tres países con más medallas

top3 = df.sort_values(by='Total', ascending=False).head(3)
print(top3)

    Oro  Plata  Bronce  Total                        Pais
25   39     41      33    113   Estados Unidos de America
72   38     32      18     88  Republica Popular de China
73    2     28      23     71                         ROC

In [10]:
min10medals = df[df['Total'] > 10]
min10medals

    Oro  Plata  Bronce  Total                        Pais
2    17      7      22     46                   Australia
11    7      6       8     21                      Brazil
14    7      6      11     24                      Canada
15    2      4       6     12              Chinese Taipei
19    7      3       5     15                        Cuba
20    4      4       3     11              Czech Republic
21    3      4       4     11                     Denmark
25   39     41      33    113   Estados Unidos de America
30    1     12      11     33                      France
32    1     11      16     37                     Germany
34   22     21      22     65                Gran Bretana
46   27     14      17     58                       Japon
60    1     12      14     36                 Netherlands
66    4      5       5     14                      Poland
72   38     32      18     88  Republica Popular de China
73    2     28      23     71                         ROC
81    3      8       6     17                       Spain
83    3      4       6     13                 Switzerland
87    2      2       9     13                      Turkey
90    1      6      12     19                     Ukraine

In [17]:
df.sort_values(by='Total', ascending=False).head(25)

    Oro  Plata  Bronce  Total                        Pais
25   39     41      33    113   Estados Unidos de America
72   38     32      18     88  Republica Popular de China
73    2     28      23     71                         ROC
34   22     21      22     65                Gran Bretana
46   27     14      17     58                       Japon
2    17      7      22     46                   Australia
32    1     11      16     37                     Germany
60    1     12      14     36                 Netherlands
30    1     12      11     33                      France
14    7      6      11     24                      Canada
11    7      6       8     21                      Brazil
90    1      6      12     19                     Ukraine
81    3      8       6     17                       Spain
19    7      3       5     15                        Cuba
66    4      5       5     14                      Poland
83    3      4       6     13                 Switzerland
87    2      2       9     13                      Turkey
15    2      4       6     12              Chinese Taipei
21    3      4       4     11                     Denmark
20    4      4       3     11              Czech Republic
77    3      1       5      9                      Serbia
45    4      1       4      9                     Jamaica
82    3      6       0      9                      Sweden
48    0      0       8      8                  Kazakhstan
17    3      3       2      8                     Croatia