1. Lectura de datos
2. Fusión de datos
3. Tratamiento de datos
4. Análisis de Ventas
- Producto más vendido
- Mes con más ventas
5. Datos agrupados por categoría de producto y analizar ventas por categoría
6. Guardar el df como un csv

In [4]:
# 1. Lectura de datos
import pandas as pd
df1 = pd.read_csv('source/Datos_Ventas_Tienda.csv')
df2 = pd.read_csv('source/Datos_Ventas_Tienda2.csv')

In [5]:
df1.head()
df1.shape
df1.info()
df1.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            1000 non-null   str
 1   Producto         1000 non-null   str
 2   Cantidad         1000 non-null   int64
 3   Precio Unitario  1000 non-null   int64
 4   Total Venta      1000 non-null   int64
dtypes: int64(3), str(2)
memory usage: 39.2 KB

          Cantidad  Precio Unitario  Total Venta
count  1000.000000      1000.000000  1000.000000
mean      5.500000        64.140000   350.650000
std       2.892467        72.345658   477.861936
min       1.000000        10.000000    10.000000
25%       3.000000        20.000000    70.000000
50%       5.000000        30.000000   150.000000
75%       8.000000        50.000000   400.000000
max      10.000000       200.000000  2000.000000

In [6]:
df2.head()
df2.shape
df2.info()
df2.describe()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            50 non-null     str
 1   Producto         50 non-null     str
 2   Cantidad         50 non-null     int64
 3   Precio Unitario  50 non-null     int64
 4   Total Venta      50 non-null     int64
dtypes: int64(3), str(2)
memory usage: 2.1 KB

        Cantidad  Precio Unitario  Total Venta
count  50.000000        50.000000    50.000000
mean    5.300000        70.200000   332.000000
std     2.697315        74.764665   389.049076
min     1.000000        10.000000    10.000000
25%     3.000000        20.000000    90.000000
50%     5.000000        30.000000   190.000000
75%     8.000000        50.000000   375.000000
max    10.000000       200.000000  1800.000000

In [7]:
# 2. Fusión de datos
df = pd.merge(df1, df2, how = 'outer')

In [15]:
print(df.head())
print('-'*30)
print(df.shape)
print('-'*30)
df.info()
print('-'*30)
df.describe()

       Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0   1/1/2023   Alimentos         2               10           20
1   1/1/2023   Alimentos         3               10           30
2   1/1/2023      Libros         8               20          160
3  1/10/2023   Alimentos         2               10           20
4  1/10/2023  Electrónic         8              200         1600
------------------------------
(1048, 5)
------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            1048 non-null   str
 1   Producto         1048 non-null   str
 2   Cantidad         1048 non-null   int64
 3   Precio Unitario  1048 non-null   int64
 4   Total Venta      1048 non-null   int64
dtypes: int64(3), str(2)
memory usage: 41.1 KB
------------------------------

          Cantidad  Precio Unitario  Total Venta
count  1048.000000      1048.000000  1048.000000
mean      5.492366        64.513359   350.324427
std       2.880945        72.479301   474.146788
min       1.000000        10.000000    10.000000
25%       3.000000        20.000000    70.000000
50%       5.000000        30.000000   155.000000
75%       8.000000        50.000000   400.000000
max      10.000000       200.000000  2000.000000

In [20]:
# 3. Tratamiento de datos

df['Fecha'] = pd.to_datetime(arg = df['Fecha'], format = '%m/%d/%Y')
print(df)

          Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0    2023-01-01   Alimentos         2               10           20
1    2023-01-01   Alimentos         3               10           30
2    2023-01-01      Libros         8               20          160
3    2023-01-10   Alimentos         2               10           20
4    2023-01-10  Electrónic         8              200         1600
...         ...         ...       ...              ...          ...
1043 2023-09-07      Libros         5               20          100
1044 2023-09-07      Libros         9               20          180
1045 2023-09-07        Ropa         3               50          150
1046 2023-09-08   Alimentos         7               10           70
1047 2023-09-08      Libros         3               20           60

[1048 rows x 5 columns]